### ISSUE TITLE
jQuery 3.5 compat

### ISSUE THREAD

**Issue by mf182407** [mbegan/Okta-Identity-Cloud-for-Splunk#44]
the lastest 2.25.21 release of this app says there were jquery compat updates, but when splunk runs the check, it is still flagged as not jquery 3.5 compat. is there going to be a release in the future to be jquery 3.5 compat?

thanks

**Comment by ghost** [comment]
+1, I have clients with Splunk who are getting emails about this app not being jquery 3.5 compatible. Is this just a case of certain files needing jquery dependencies updated a version number or is this a different problem?

**Comment by simonsigre** [comment]
@nick and others … as I understand Matt has moved on from Okta and I’ve reached out to the Okta integrations team to try and coordinate what a viable solution is .

Event streams seem to be the safest at the moment; we have a lot of customers using this component so we will keep you abreast

**Comment by mbegan** [comment]
[Reports of my death/departure are greatly exaggerated](https://www.dictionary.com/browse/the-reports-of-my-death-are-greatly-exaggerated)
;-)

I was under the impression that the latest version released on splunkbase had addressed the artifacts that were missing to make it happy with jquery.

![image](https://user-images.githubusercontent.com/11389580/160953835-672ec748-5ab4-45f7-9b49-c2270f8ba4e5.png)

**Comment by edaemon** [comment]
@mbegan, it seems like there's still something missing:

![image](https://user-images.githubusercontent.com/19846640/161791199-a77f5149-da07-43c3-99ae-c0c60c72cc1a.png)

Unfortunately I don't see any way to get more detailed information.

**Comment by DonBlake** [comment]
Team, What is the plan from the development team to address the issue, or is this being EOL'd?  Also, aside from being flagged by the Splunk product, are there any known exposures and/or attack vectors if this product is in use?

**Comment by AHCL1** [comment]
Any update on this? Still getting flagged by Splunk

**Comment by sushaw** [comment]
+1 , we also have this issue

**Comment by RubberJengaBlocks** [comment]
@mbegan @simonsigre @DonBlake, After speaking with a Splunk engineer, it appears that there is still one file referencing an older version of JQuery. Is this ID correct, and can this reference be updated?

**Incompatible file referencing JQuery v2.1.0:** /TA-Okta_Identity_Cloud_for_Splunk/appserver/static/js/build/common.js
**Add-on being flagged by the Upgrade Readiness App:** Okta Identity Cloud Add-on for Splunk

Thank you

**Comment by animetauren** [comment]
Just to clarify: 

Okta Identity Cloud Add-on for Splunk v2.25.21 will run on Splunk Cloud, with no issues since this TA does not consume custom JS to run, @mbegan correct me if I mistaken. 

The error listed above referencing jQuery v2.1.0 is the output result from the [Upgrade Readiness App (URA)](https://docs.splunk.com/Documentation/UpgradejQuery/1/UpgradejQuery/JURAoverview).

@mbegan That said this TA is still being flagged, are you using the Splunk Add-On Builder? If so please make sure you using v4.0+ which will fix the common.js issue being flagged. [Source](https://community.splunk.com/t5/Developing-for-Splunk-Enterprise/Do-apps-built-using-Add-On-Builder-require-changes-for-JQuery-3/m-p/562828#M9383)

**Comment by poiromaniax** [comment]
@mbegan Is there any update around this issue?

Now that Splunk 9.0 is out there, and vulnerabilities have been published - moving to 9.0 is definitely a near reality.....

**Comment by rolltidega** [comment]
@mbegan I am looking for an update to this issue as well.  Thanks for all you do!

**Comment by awx-vsyr** [comment]
+1

**Comment by toddmhawkins** [comment]
Being a Splunk Cloud customer they want this upgraded but without the new version supported by Splunk cloud I can't update it so I'm stuck. Hopefully you all are close to getting the new version Splunk Cloud certified.

**Comment by zingagent** [comment]
Another user here.
It seems App Inspect is failing version 2.25.21 and hence blocked from Cloud.

I downloaded the package and pushed it through and I'll try to attach the full report here.  (json output sorry)

Essentially it's failing 3 things, and I think all of those things get solved by upgrading add-on builder to latest version
You can do that by exporting the project and importing again with new add-on builder version.

The fails:
- insecure javascript file: TA-Okta_Identity_Cloud_for_Splunk/appserver/static/js/build/common.js
- outdated Splunk SDK for Python
- use of old version of Add-on Builder

Now since that hasn't happened yet, I'm wondering whether original add-on builder project has been lost or sidelined.

[okta.txt](https://github.com/mbegan/Okta-Identity-Cloud-for-Splunk/files/9459212/okta.txt)

**Comment by poiromaniax** [comment]
FYI, I installed a local version of Splunk 9.0.0.1 and installed this Okta addon to test.

It still runs on v9 without issues (that I could identify)

I dont think this info is relevant to Cloud, but for on-prem this shouldnt block upgrading......

**Comment by mf182407** [comment]
thanks for all the replies. unfortunately this still seems to be an issue. but fortunately, after being upgraded to 9.x i am not noticing any issues. 

that doesn't mean it cant break in the future, though

**Comment by s-m-p** [comment]
Hi all. I just wanted to chime in here to say this TA has been superseded by one written and supported by Splunk, the [Splunk Add-on for Okta Identity Cloud](https://splunkbase.splunk.com/app/6553). 

I personally have not transitioned yet since I only stumbled across this recently, but I plan to. Clearly this TA not getting much attention anymore based on this and other Github reported issues. And I don't say that to be critical of the maintainer of this repo - this TA has been vital to me for several years now and I am deeply grateful it was shared at all. I've had several situations myself where problems with this TA suddenly appear and Splunk has been absolutely unwilling to provide any support. It has put me in a really difficult spot. So from a support perspective, it's in my best interest to move to the Splunk-supported TA to eliminate any excuses not to provide support.

Cheers!

**Comment by mf182407** [comment]
good comms. the docs state that it is intended to replace this app, but there is not 100% feature parity at this time. 2023 q1 is the estimated date.

thanks for sharing the info above!
